default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'postgres' } %>

development:
  <<: *default
  database: ss_backend_development

test:
  <<: *default
  database: ss_backend_test

production:
  <<: *default
  database: ss_backend_production
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
